src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/hub/Hub.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntries.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java, src/main/java/net/floodlightcontroller/util/ActionUtils.java, src/main/java/net/floodlightcontroller/util/InstructionUtils.java, src/main/java/net/floodlightcontroller/util/MatchUtils.java, src/main/resources/logback-test.xml
Fixed bugs in InstructionUtils and added ability to match on masked fields (trial with VlanVid). Tidied up/removed some old comments.
=> Bug fixes and initial masked-matching support for SFP.

src/main/java/net/floodlightcontroller/firewall/FirewallStorageRulesResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallSubnetMaskResource.java, src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java
(1) Addressed issue #471 
(2) Pulled down Firewall merge changes and fixed a couple unused import and variable warnings
=> Small bug in LinkDiscoveryManager + Some housekeeping after merging Firewall pull request

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java, src/main/java/net/floodlightcontroller/staticflowentry/web/StaticFlowEntryPusherResource.java, src/main/resources/META-INF/services/net.floodlightcontroller.core.module.IFloodlightModule, src/main/resources/logback-test.xml, src/test/java/net/floodlightcontroller/learningswitch/LearningSwitchTest.java
LearningSwitch fixes/optimizations.
=> Finally got around to fixing LearningSwitch.

src/main/java/org/openflow/protocol/statistics/OFVendorStatistics.java
Added comment for the newly added function .
=> Added Comment OFVendorStatistics.java

README.md
Made the README.md a bit easier to read by adding some additional markdown formatting.
=> update formatting of README.md

src/main/resources/learningswitch.properties, src/main/resources/neutron.properties
Updated properties files to include more recent controller features (security, handshake, etc).
=> Updated LearningSwitch and Neutron properties files.

src/main/java/net/floodlightcontroller/core/types/MacVlanPair.java
This was useful to have during debugging. A simple change.
=> Added a more useful toString() method.

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java
Added feature to set SEND_FLOW_REM flag in Forwarding module. It is set to false by default.
=> Added feature to set SEND_FLOW_REM flag in the flow_mod messages created in the Forwarding module

pom.xml
Small patch to include the aforementioned files in the final jar.
=> modified pom.xml to include LICENSE.txt, NOTICE.txt and README.md

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java
Reverts floodlight/floodlight#555
Fix possible missing import...
=> Revert "writePacketOutForPacketIn to OFMessageUtils"

src/main/java/net/floodlightcontroller/packet/Ethernet.java, src/main/java/net/floodlightcontroller/packet/IPv6.java, src/test/java/net/floodlightcontroller/packet/IPv6Test.java
Hi Ryan. I couldn't figure out how to modify my pull request to change branches/commits, so I just closed it and started this new one. This contains everything the last one did except the LoxiGen stuff.
=> IPv6 (New)

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java
Reverts floodlight/floodlight#559
=> Revert "Revert "writePacketOutForPacketIn to OFMessageUtils""

src/main/java/net/floodlightcontroller/accesscontrollist/ACL.java, src/main/java/net/floodlightcontroller/accesscontrollist/IACLService.java
- fix bug in processing allowing ACL rule
- update Javadoc
=> Refactoring ACL.java and IACLService.java

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchManager.java
Patched features request/reply via REST API. Wrote a stub for OF-DPA default flow insertion -- still a work in progress. It's an uncalled function right now, so it will not hurt anything.
=> Features request via REST API bug fix and start on OF-DPA support

src/main/java/net/floodlightcontroller/util/OFDPAUtils.java
Ooops. Forgot to include the new source file for OFDPAUtils (hiding in untracked files)...
=> Adding OFDPAUtils.java

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java
Patch Forwarding's pushPacket and pushRoute. We do not want to push a packet if the command is delete or delete-strict.
=> Patch Forwarding's pushRoute and pushPacket

.travis.yml, README.md, pom.xml
Add in Travis-CI build yml file. Fix Maven dependency typo. Update README with headers and build status.
=> Initial commit to add in Travis-CI automated testing

src/main/java/net/floodlightcontroller/accesscontrollist/ACL.java, src/main/java/net/floodlightcontroller/accesscontrollist/ACLRule.java, src/main/java/net/floodlightcontroller/accesscontrollist/IACLService.java, src/main/java/net/floodlightcontroller/accesscontrollist/ap/AP.java, src/main/java/net/floodlightcontroller/accesscontrollist/ap/APManager.java, src/main/java/net/floodlightcontroller/accesscontrollist/util/IPAddressUtil.java, src/main/java/net/floodlightcontroller/accesscontrollist/web/ACLRuleResource.java, src/main/java/net/floodlightcontroller/accesscontrollist/web/ACLWebRoutable.java, src/main/java/net/floodlightcontroller/accesscontrollist/web/ClearACRulesResource.java
Hi,
I need to update adviser information in the copyright comment. Thanks!
Best Regards,
Alex
=> Update adviser information in the copyright comment.

src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java, src/test/java/net/floodlightcontroller/core/internal/MockOFConnection.java, src/test/java/net/floodlightcontroller/core/internal/MockOFSwitchImpl.java, src/test/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManagerTest.java
Addresses https://github.com/floodlight/floodlight/issues/642
=> Do not send LLDP if we're in SLAVE role

src/main/java/net/floodlightcontroller/util/ActionUtils.java, src/main/java/net/floodlightcontroller/util/MatchUtils.java
Update MatchUtils and ActionUtils to fully support parsing 32-bit signed and unsigned port numbers in hex and decimal from strings. Also improved and added more keywords for ingress and output ports to support local, table, normal, controller, in_port, all, and flood without care for the openflow version (which might encode this special ports differently, e.g. OF1.1-'s LOCAL is 0xfffe, while it's 0xfffffffe in OF1.2+.
This addresses https://github.com/floodlight/floodlight/issues/527 (ignoring cookie, which wasn't a bug).
Also, this PR makes an optimization and replaces all Short, Integer, and Long valueOf() functions with parseShort(), parseInt(), and parseLong(), which return the primitive types and don't wrap them in objects.
=> Improve in_port match and output action handling in Static Flow Pusher

src/main/java/net/floodlightcontroller/restserver/RestApiServer.java, src/main/java/net/floodlightcontroller/ui/web/StaticWebRoutable.java, src/main/resources/floodlightdefault.properties
@cbarrin This will be useful when switching controllers in the updating web UI
=> Add ability to permit all origins when using REST API

src/main/java/net/floodlightcontroller/topology/Archipelago.java, src/main/java/net/floodlightcontroller/topology/ITopologyService.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java, src/main/java/net/floodlightcontroller/topology/TopologyManager.java
I finally (correctly) added in the archipelago functionality to floodlight. All of the tests pass! Let me know if there's anything else I need to do. 
Also, IntelliJ changed a bunch of the imports. It says they're optimized, but who really knows.
=> Archipelagos

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java
(1) change topology broadcast ports log level to debug
(2) fix copy-and-paste incorrect log in forwarding
(3) don't set table ID in 1.0 drop flows
=> small fixes

src/main/java/net/floodlightcontroller/util/ActionUtils.java
=> allow hex or decimal values for copy_field action parsing

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
refactor some of Forwarding's doForwardFlow to make it easier to understand
=> Forwarding tweaks

src/main/java/net/floodlightcontroller/core/web/serializers/StatsReplySerializer.java
=> REST API bug

build.xml
=> Update ant javadoc source version to 1.8

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
Only remove once, else ConcurrentModificationExceptions will ensue...
=> Fix ConcurrentModifcationException in Forwarding

src/main/java/net/floodlightcontroller/util/MatchUtils.java
Fixed the IP_TOS match bug caused by passing incorrect arguments to ECN and DSCP constructors.
=> IP_TOS Match bug fix

src/main/java/net/floodlightcontroller/util/ActionUtils.java, src/main/java/net/floodlightcontroller/util/MatchUtils.java
Fixed a bug that would cause a set_dst_port action to result in a set_src_port action.
=> Fixed copy paste bug in ActionUtils

src/main/java/net/floodlightcontroller/cpanalyzer/CPAnalyzer.java, src/main/java/net/floodlightcontroller/cpanalyzer/ICPAnalyzerService.java, src/main/resources/META-INF/services/net.floodlightcontroller.core.module.IFloodlightModule
@cbarrin Add CPAnalyzer module for more easily debugging the control plane from a single module
=> Add CPAnalyzer module

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java
Fixed an exception caused by wrong OF version for flow
=> Learningswitch OF Exception from InstructionApplyActions fixed

src/main/java/net/floodlightcontroller/util/ActionUtils.java
Missed a break statement in case SET_QUEUE, which caused an error when parsing SET_QUEUE;
=> Fix bug for ActionUtils.java

src/main/java/net/floodlightcontroller/restserver/RestApiServer.java
=> fix CORS bug

src/main/java/net/floodlightcontroller/core/internal/OFChannelHandler.java, src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java, src/main/java/org/sdnplatform/sync/internal/SyncTorture.java
should use "System.nanoTime/1000000" instead of "System.currentTimeMillis()" as latency should be a elapse time, not the clock time.
=> Fix the latency computation

src/main/java/net/floodlightcontroller/util/ActionUtils.java
Hello Qing,I'm a Liu Zhifeng‘s partner.My name is Chen Weinan. We have already talked on the Google group many times.I have solved the problem that Set_field->tunnel_id error when using static entry pusher.All changes are in the Actionutil.java.
=> add tunnel->xxx

src/main/java/net/floodlightcontroller/statistics/StatisticsCollector.java
Fix for #806 -- shall use double to avoid long/long operation to cause inaccurate truncation. 
CC: @rizard @geddings   
trivial 
- [* ] Bug fix (non-breaking change which fixes an issue)
=> #806 - Accurate computation of elapsed time

docs/README.md, docs/tutorials/ProcessingAPacketInMessage.md, docs/tutorials/README.md
This PR adds a simple example in the proper format in order to be consumed by [GitBook](https://www.gitbook.com). 
For reference, GitBook will act as the new home for our project documentation. 
The PR includes a readme and a single tutorial that has been converted into markdown. We can use it as a model for porting over the rest of the tutorials and creating updated, simplified documentation.
Our current documentation is stored in Confluence and is deeply nested, difficult to find, and has grown unorganized over the years. By migrating to GitBook, we can flatten out our documentation hierarchy and lower the bar for users to get up and running with Floodlight.
I've tested this using my fork and directing GitBook to use the documentation there.
=> Add simple documentation example for GitBook support

.gitbook.yaml
GitBook allows for formatting through a configuration file. This PR adds that file and points to GitBook to the `docs` directory.
`.gitbook.yaml` is used by GitBook to specify different formatting options. More details can be found [here.](https://docs.gitbook.com/integrations/github/content-configuration)
Currently, GitBook is recursively searching the project for markdown files. It's pulling in the issue and PR templates, along with some module documentation (which may be useful to have later). We need to direct GitBook to the default documentation directory.
=> Add gitbook configuration file for formatting

pom.xml, src/test/java/net/floodlightcontroller/core/test/TestEventLoop.java
One more bump; I did mean to move netty to latest (4.1.5~1~0.Final) not 4.0.51.Final.
=> bump netty to 4.1.50.Final
