floodlight/floodlight

logback.xml, src/main/java/net/floodlightcontroller/core/web/serializers/MatchSerializer.java, src/main/java/net/floodlightcontroller/core/web/serializers/OFInstructionListSerializer.java, src/main/java/net/floodlightcontroller/staticflowentry/IStaticFlowEntryPusherService.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntries.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java, src/main/java/net/floodlightcontroller/util/InstructionUtils.java, src/main/java/net/floodlightcontroller/util/MatchUtils.java
SFP supports hard/idle timouts w/drawback of needlessly sending flow_del to switch (which gets silently discarded). This is a good first step but needs to be followed up with a solution to the redundant flow_del msg. Also, patched MatchSerializer to display masks if present and fixed a bug in OFInstructionListSerializer for metadata and goto_table instructions.
Added masking support to all SFP match fields. OVS supports some masked fields that are not defined in the OF1.3 spec. Oddly enough, OVS returns a bad-match error message even though the flow gets inserted with the supposedly "bad" mask. I suppose that message is due to the OF protocol not supporting it. OVS should squelch it if it supports it though. In any case, Floodlight is equipped to support all present MatchFields as masked …
=> SFP support for idle/hard timeouts

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/debugcounter/CounterNode.java, src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/testmodule/TestModule.java, src/main/resources/floodlightdefault.properties, src/main/resources/logback-test.xml, src/test/java/net/floodlightcontroller/staticflowentry/StaticFlowTests.java
(1) Allow switches to handshake that do not support barrier messages (logs a warning...HP ProCurve is one such switch)
(2) Correctly apply flows for packets that pass the firewall (ignore the match that allowed the firewall to pass the packet and allow forwarding to route it)
(3) Bug fix in DebugCounterService. Don't step off the beginning of the list if it's empty (access item -1).
=> Misc patches

src/main/java/net/floodlightcontroller/firewall/FirewallDisableResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallEnableResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallResourceBase.java, src/main/java/net/floodlightcontroller/firewall/FirewallStatusResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallStorageRulesResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallSubnetMaskResource.java, src/main/java/net/floodlightcontroller/firewall/FirewallWebRoutable.java
This patch solves the first half of issue [https://github.com/floodlight/floodlight/issues/488]
The existing REST API for enabling and disabling the firewall relies on GET requests.
Best practices dictate that GET requests should not change the state of the system.
This patch disables the GET semantics and replaces it with a PUT based endpoint to enable/disable the firewall.
Also refactored the FirewallResource class into multiple smaller classes to make URL routing clearer.
=> Refactored firewall REST api.  Allow POST for firewall enable/disable.

src/main/java/net/floodlightcontroller/staticflowentry/web/StaticFlowEntryPusherResource.java
In line 329 of StaticFlowEntryPusherResource.java, the word "flow mod"
is spelled as "flod mod".
Just encountered that when using the rest api, so I fixed it.
=> Correct the spelling error

src/main/java/net/floodlightcontroller/core/OFConnection.java, src/main/java/net/floodlightcontroller/core/OFSwitch.java, src/main/java/net/floodlightcontroller/core/internal/IOFConnectionListener.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchManager.java, src/main/java/net/floodlightcontroller/core/internal/RoleManager.java, src/main/java/net/floodlightcontroller/core/web/ControllerRoleResource.java, src/main/java/net/floodlightcontroller/core/web/CoreWebRoutable.java, src/main/java/net/floodlightcontroller/core/web/SwitchRoleResource.java, src/main/java/net/floodlightcontroller/core/web/serializers/StatsReplySerializer.java, src/main/java/net/floodlightcontroller/firewall/Firewall.java, src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java, src/main/resources/floodlightdefault.properties, src/test/java/net/floodlightcontroller/core/OFSwitchBaseTest.java
Had to tap into the connection and handshake handlers to make this work with the given structure, but modules can send role requests now, and the switch(es) will automatically update state(s) appropriately.
Reworked REST API at /wm/core/switch/<dpid-or-"all">/role/json
Can list using GET as above or POST '{"role":"MASTER | SLAVE | EQUAL | NOCHANGE | OTHER"}'
=> First round of support for changing switch roles via modules and REST API.

src/main/java/net/floodlightcontroller/core/web/serializers/OFActionListSerializer.java, src/main/java/net/floodlightcontroller/util/ActionUtils.java
Fixed action serializer for actions that do not have values e.g. strip_vlan and such. Added in a 'n/a' value for the JSON key's value. Perhaps we should rethink how a list of actions is serialized to avoid the 'n/a' all together.
=> Fixed action serializer for actions that do not have values

src/main/resources/web/js/main.js
In the Web UI footer, the link cannot lead user to the correct
site. This patch fix it.
=> Fix Web UI link error

src/main/java/net/floodlightcontroller/core/web/serializers/OFActionListSerializer.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntries.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchHandlerTestBase.java
Static Flow Pusher:
-- when you push a flow from another module, masks are applied correctly in storage
-- null pointer exception fixed when pushing to a switch that is not connected. The flow will be removed.
-- JSON serialize output for actions lists each action in a single string for cases of multiple, sequential actions of the same type, e.g. output
Unit Tests:
-- see the commit log. Fixed a dependency issue.
=> Fixed a couple SFP bugs and a long-time unit test dependency bug

pom.xml, src/test/java/net/floodlightcontroller/core/OFSwitchBaseTest.java
Fixed one failed unit test (see #548)
=> fixed failed unit test because of new handleOutgoingMessage() in IOFSwitchManager

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java
- Created writePacketOutForPacketIn function in OFMessageUtils based on the one from LearningSwitch.
- Modified writePacketOutForPacketIn in LearningSwitch to use the one in OFMessageUtils and still increment the counterPacketOut.
- Ran LearningSwitchTest and both tests passed.
=> writePacketOutForPacketIn to OFMessageUtils

src/main/java/net/floodlightcontroller/loadbalancer/LoadBalancer.java
The deference violations (may incur by data races) need to be fixed in LoadBalancer module. Those bugs can cause a serious vulnerability, .i.e., blocking forwarding module.
=> fix data races in LoadBalancer module

src/main/java/net/floodlightcontroller/core/internal/OFChannelHandler.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchManager.java, src/main/java/net/floodlightcontroller/core/internal/OpenflowPipelineFactory.java, src/main/java/net/floodlightcontroller/core/web/serializers/OXMSerializer.java, src/main/java/net/floodlightcontroller/core/web/serializers/StatsReplySerializer.java, src/main/java/net/floodlightcontroller/util/MatchUtils.java, src/main/resources/floodlightdefault.properties, src/test/java/net/floodlightcontroller/core/internal/OFChannelHandlerVer10Test.java, src/test/java/net/floodlightcontroller/core/internal/OFChannelHandlerVer13Test.java
OpenFlow 1.3.1 defines a version bitmap to make determining a common OpenFlow version easier. If both the switch and the controller send version bitmaps in the hello, the highest common OpenFlow version in the bitmap should be used as the OpenFlow protocol. If both do not support the version bitmap (which is never required and only optional), then the lesser of the two OpenFlow versions in the hello message headers should be used. The version in the hello message header should always be the highest supported version of the sender.
So, clearly it's beneficial to use the version bitmap and not the lesser of the header versions, since the latter means the sender must support each OpenFlow version up to the version advertised in the header (which isn't the case for many hardware switches and …
=> Lots of good stuff for OpenFlow protocol version negotiation

src/main/java/net/floodlightcontroller/linkdiscovery/ILinkDiscoveryService.java, src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java
Fix deference bugs in LinkDiscoveryManager module. Those bugs stems from a potential race condition in OFSwitch.switchDisconnected() and OFSwitch.getSwitch() in OFSwtichManager module. I have also modified the interface generateLLDPMessage() in ILinkDiscoveryService to avoid atomicity violations. 
The unit test is passed for those modifications.
=> fix race conditions in LinkDiscoveryManager module

src/main/java/net/floodlightcontroller/core/web/serializers/OXMSerializer.java, src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java
Added an NXM to the new OXM serialization/deserialization class.
Fixed an OpenFlow version bug in the SFP, where a table ID would be asked for in the flow removed message in OF1.0 (a no-no) and the hard timeout would be asked of the flow removed message in OF1.0 and OF1.1 (also a no-no -- not introduced until OF1.2).
=> Minor OXM serializer patch and Static Flow Pusher bug fix

src/main/java/net/floodlightcontroller/core/internal/OFChannelHandler.java, src/main/java/net/floodlightcontroller/util/OFDPAUtils.java, src/main/java/net/floodlightcontroller/util/OFPortMode.java, src/main/java/net/floodlightcontroller/util/OFPortModeTuple.java
Some non-tested updates to the OF-DPA utilities. Still a work in progress, but almost done.
Ignore packet-in message in the WaitFeaturesReply state in OFChannelHandler. Some switches like to send packet-ins even though we don't know the DPID yet and cannot process them.
=> OF-DPA updates and ignore PI on wait features

src/main/java/net/floodlightcontroller/core/OFConnection.java, src/main/java/net/floodlightcontroller/core/internal/OFChannelHandler.java
Fix bug in controller OF protocol version when we set our default below 1.3. We now honor OF1.2 and under's lack of version bitmaps in the hello.
Also, remove some unnecessary spaces. I hate those.
=> Quick bug fix in OFHello composition for OF versions 1.0, 1.1, and 1.2. 

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchHandlerTestBase.java
Patched the handshake so that on transition to master, we guarantee the order of flow table operations (e.g. clear, adding table-miss flows, and IOFSwitchListener module switchAdded/switchActivated listener operations). Barriers are used inbetween all such operations.
=> Improve handshake reliability with user modules that implement IOFSwitchListener and modify flow table on switchAdded event

src/main/java/net/floodlightcontroller/core/internal/OFChannelHandler.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java
All switches should support table-features if they are OF1.3 switches. But in the case they do not, then we should still insert the table-miss flows anyway.
TODO: Tweak IOFSwitch to properly allow access to specific switch table IDs
=> Allow switches that don't support table-features message to still receive table-miss flows

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java, src/main/java/net/floodlightcontroller/topology/TopologyManager.java, src/main/resources/floodlightdefault.properties
Added ability to disable ARP flows in Forwarding. Many hardware switches cannot handle ARP flows. ARP flows on by default; turn off/on via 'flood-arp' in floodlightdefault.properties. Also, finished integrating new topology service/routing into Forwarding. This required a few more null checks to handle cases where packet-ins are received while the controller is starting/still discovering the topology/links.
Also, changed many ForwardingBase fields to protected. Not quite sure why they were all public.
=> Finish new topology service integration by patching Forwarding + one new feature

src/main/java/net/floodlightcontroller/routing/ForwardingBase.java
Wow. Not sure how that passed. Should have run ant (outside eclipse) -- would have given the compile error. Turns out VirtualNetworkFilter required the hard and idle timeouts to be public. TODO implement getters so that nobody can change these.
=> Revert hard and idle timeout to public

src/main/java/net/floodlightcontroller/devicemanager/internal/Device.java, src/main/java/net/floodlightcontroller/devicemanager/internal/DeviceManagerImpl.java, src/main/java/net/floodlightcontroller/loadbalancer/LoadBalancer.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/java/net/floodlightcontroller/topology/ITopologyService.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java, src/main/java/net/floodlightcontroller/topology/TopologyManager.java, src/main/java/net/floodlightcontroller/topology/web/SwitchClustersResource.java, src/test/java/net/floodlightcontroller/accesscontrollist/ACLTest.java, src/test/java/net/floodlightcontroller/devicemanager/internal/DeviceManagerImplTest.java, src/test/java/net/floodlightcontroller/forwarding/ForwardingTest.java, src/test/java/net/floodlightcontroller/loadbalancer/LoadBalancerTest.java
Tidy up topology and get rid of some many redundant functions in IToologyService. For all intents and purposes, especially as the code is designed now, an OpenFlow domain is the same as an L2 domain.
Also, fix a bug that prevents outgoing broadcast ports from being queried on single-switch islands.
=> Single-switch islands list correct outgoing broadcast ports; tidy up topology service

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/topology/TopologyManager.java
Finally, finally got to the bottom of the 'simple topology' Forwarding bug.
If there is a broadcast packet that we're going to flood AND the switch is not connected to any other switch (i.e. has no links in the topology), then we just need to ignore ITopologyService's recommendation of 'null' broadcast ports and send the packet out special port FLOOD. This is an edge case workaround. Any topology with links will use the list of broadcast ports returned by the ITopologyService.
Also, if a switch has no links associated with it, we should ignore what the IRoutingService tells us ('null' route). Instead, assume the devices are on the same switch, and manually compose a route from one switch port to another.
=> Forwarding bug fix for edge-case simple topology

src/main/java/net/floodlightcontroller/firewall/FirewallRulesResource.java
The `dl_type=ARP` (or any other `dl_type`) is overwritten if `dst-ip` or `src-ip` are specified later on in the json object. I added condition that only overwrites the field if it hasn't been already specified.
=> Fix for Firewall issue #590

src/main/java/net/floodlightcontroller/staticflowentry/web/StaticFlowEntryPusherResource.java
Fixed SFP issue (https://github.com/floodlight/floodlight/issues/587) where the flow checker would allow a flow w/o a switch specified.
=> Fix SFP bug pushing flow w/o switch ID specified

src/main/java/net/floodlightcontroller/dhcpserver/DHCPSwitchFlowSetter.java, src/main/java/net/floodlightcontroller/loadbalancer/LoadBalancer.java
Fix harmful data races in LoadBalancer and DHCPSwitchFlowSetter module. A concurrent switch removal can cause null pointer exception on getSwitch() service function and incur serious logic flaws in those modules, e.g., break service chain and leak physic IP address of server replica.
=> Fix data races in LoadBalancer and DHCPSwitchFlowSetter

src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java
Fix concurrency bugs in LinkDiscoveryManager Module. In which, multiple removals on a global queue can incur exception raised and termination of the thread.
=> fix concurrency bugs in LinkDiscoveryManager Module.

src/main/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManager.java
Fix concurrency bugs in LinkDiscoveryManager Module. In which, multiple removals on a global queue can incur exception raised and termination of the thread.
=> fix concurrency bugs

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/java/net/floodlightcontroller/util/OFDPAUtils.java, src/main/java/net/floodlightcontroller/util/OFPortMode.java, src/test/java/net/floodlightcontroller/forwarding/ForwardingTest.java
Added OF-DPA helper functions to allow a user module or Forwarding to more easily insert basic learning switch flows into an OF-DPA switch. Forwarding is presently extended to detect and insert flows for an OF-DPA switch as outlined below. Forwarding assumes all switch ports are untagged/access, but OFDPAUtils supports multiple VLANs -- tagged or trunk. Forwarding can be extended to defined certain ports to be on certain VLANS if a user requires.
For convenience, OFDPAUtils has an inner class called GroupIds that allows for the easy creation of valid OF-DPA group IDs according to the OF-DPA spec. This is primarily for use within OF-DPAUtils, but can be used by user modules if needed.
OFDPAUtils allows for a user module (or Forwarding as outfitted now) to (1) detect an OF-DPA switch and …
=> Add OF-DPA helper functions

src/main/java/net/floodlightcontroller/statistics/IStatisticsService.java, src/main/java/net/floodlightcontroller/statistics/StatisticsCollector.java, src/main/java/net/floodlightcontroller/statistics/SwitchPortBandwidth.java, src/main/java/net/floodlightcontroller/statistics/web/BandwidthResource.java, src/main/java/net/floodlightcontroller/statistics/web/ConfigResource.java, src/main/java/net/floodlightcontroller/statistics/web/SwitchPortBandwidthSerializer.java, src/main/java/net/floodlightcontroller/statistics/web/SwitchStatisticsWebRoutable.java, src/main/resources/META-INF/services/net.floodlightcontroller.core.module.IFloodlightModule, src/main/resources/floodlightdefault.properties
There have been so many questions on how to collect statistics. There been even more questions on how to calculate bandwidth consumption of ports. A new module, net.floodlightcontroller.statistics.StatisticsCollector, has been created to periodically collect port statistics, paying particular attention to the RX/TX bytes of each port of each switch. The module will collect on a default interval of 10s and take the changed bytes divided by the elapsed time.
A REST API is at /wm/statistics/bandwidth/<switch-dpid>/<port-id>/json. It will allow the user to query for the *most recent* statistics values for the switch(es) and port(s) in question.
This is a work in progress and needs to be cleaned up a bit before being pulled. Expect commits in the near future.
=> Initial statistics module commit

src/main/java/net/floodlightcontroller/core/IOFMessageWriter.java, src/main/java/net/floodlightcontroller/core/IOFSwitch.java, src/main/java/net/floodlightcontroller/core/internal/NullConnection.java, src/main/java/net/floodlightcontroller/core/internal/OFConnection.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitch.java, src/main/java/net/floodlightcontroller/util/IterableUtils.java, src/test/java/net/floodlightcontroller/core/internal/MockOFConnection.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchBaseTest.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchHandlerTestBase.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchTest.java, src/test/java/net/floodlightcontroller/forwarding/ForwardingTest.java, src/test/java/net/floodlightcontroller/hub/HubTest.java, src/test/java/net/floodlightcontroller/learningswitch/LearningSwitchTest.java, src/test/java/net/floodlightcontroller/linkdiscovery/internal/LinkDiscoveryManagerTest.java, src/test/java/net/floodlightcontroller/loadbalancer/LoadBalancerTest.java, src/test/java/net/floodlightcontroller/staticflowentry/StaticFlowTests.java, src/test/java/net/floodlightcontroller/util/OFMessageDamperMockSwitch.java
@AndreMantas thanks for the support coming up with this solution!
Although the OpenFlow protocol dictates that an error message should be returned from the switch if any invalid, state-modifying message is sent to it from a controller in the SLAVE role, it is better to block the messages locally on the controller to avoid burdening the switch with such messages it will inevitably be required to process and kick back in error.
The previous filter in place in Floodlight filtered out *all* messages sent to a switch when a controller was in SLAVE role to that switch. A controller is however allowed to read the state from the switch with stats/multipart requests, as well as set its asynchronous communication preferences for events dispatched from the switch to the controller. The new …
=> Add ability to filter outbound messages while in SLAVE role

src/main/java/net/floodlightcontroller/core/internal/OFSwitch.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/java/net/floodlightcontroller/util/FlowModUtils.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchBaseTest.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchTest.java
Fix OF1.4 table features properties byte-align to 8 bytes. This required a Loxi update. Also updated handshake handler to not use action but instead instructions w/apply-actions.
In an upcoming commit, will update Forwarding and others that use the flowMod.setActions(actions) shortcut for flowMod.setInstructions(Collections.singletonList((OFInstruction) actions)). Either that, or will update Loxi again with the prewritten Java for an OF1.4 equivalent shortcut.
=> OF1.4 bug fixes

src/main/java/net/floodlightcontroller/core/IControllerCompletionListener.java
Hi,
I apparently was so focused on functionality that I forgot legalise. I have checked and licenses are compatible. 
Sorry for the inconvenience,
/PA
=> Included NetIDE header under EPL

src/main/java/net/floodlightcontroller/core/web/serializers/StatsReplySerializer.java
Add durationNSeconds to flow-stats REST API output. Forgot about it in the serializer.
=> Add nanoseconds to flow-stats REST API output

src/main/java/org/sdnplatform/sync/internal/store/JavaDBStorageEngine.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2259 - “Null pointers should not be dereferenced”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S2259
Please let me know if you have any questions.
Sameer Misger
=> Fixing squid:S2259 - Null pointers should not be dereferenced

floodlight.sh
This is so you can use floodlight arguments, such as "-cf <config_file>", when executing the script.
=> Passed script arguments to floodlight

src/main/java/net/floodlightcontroller/packet/Ethernet.java
For Ethernet types not in Ethernet.etherTypeClassMap, the deserialization would set the payload to the whole data array (including the mac addresses and eth type) instead of the rest of the data array.
For example, this would fail to print:
Ethernet l2 = new Ethernet();
l2.setEtherType(EthType.of(65535)); // some type
l2.setSourceMACAddress(MacAddress.of("00:00:00:00:00:01"));
l2.setDestinationMACAddress(MacAddress.BROADCAST);
Data packetData = new Data();
packetData.setData("some string".getBytes());
l2.setPayload(packetData);
byte[] l2bytes = l2.serialize();
Ethernet l2d = new Ethernet();
l2d.deserialize(l2bytes, 0, l2bytes.length);
Data packetDataDeserialized = (Data) l2d.getPayload();
// printing "new String(packetDataDeserialized.getData())" gives "?????"
I ran the JUnit tests in …
=> deserialize fix for not-known Ethernet types

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java
This causes build issues for those who do not have the right language packs installed to support curved apostrophes.
=> Don't use 'fancy' apostrophes, which are not ASCII

src/main/java/net/floodlightcontroller/devicemanager/web/DeviceResource.java
Please consider this change to the REST API.  I expect to work through the rest of the resource calls if this change is adopted.
Many REST ingest schemes (e.g. Graylog "JSON path from HTTP") expect servers to return well-formed JSON objects.  Floodlight is sometimes returning values that lack root objects.  This can make ingestion engines ignore "non-JSON header fields" until they encounter the start of an object (that is, a "{" character).  In the case of a '/wm/device/' query from Graylog, this means only the first device in the list is recognized.
Was:
[ \<list-of-device-objects\> ]
Now:
{ 'devices' : [ \<list-of-device-objects\> ] }
=> Changed DeviceResource to return a JSON object instead of returning a list.

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java, src/test/java/net/floodlightcontroller/devicemanager/internal/DeviceManagerImplTest.java
(1) @cbarrin Patched archipelagos code to account for case where there are no clusters adjoined by external links to form an archipelago. In this case, each cluster is its own archipelago.
(2) Ignore DeviceManagerImpl packet-in unit tests util we figure out why they periodically fail. I think this is an issue with the tests themselves and not the device manager.
(3) Make some log messages better/more informative, and don't display the entire stack trace if we can't compute a route. This is relatively common when processing lots of packet-in messages and discovering the initial topology at the same time.
=> Bug fix and improvements

pom.xml
The pom.xml in the release v1.2 branch still contains a SNAPSHOT tag, causing issues with some deployments.
=> Changed version in pom.xml to 1.2 for release

src/main/java/net/floodlightcontroller/staticentry/StaticEntryPusher.java, src/main/java/net/floodlightcontroller/util/ActionUtils.java
convert integer DPIDs specified to the SEP to DatapathId to prevent duplicate DPID flow sets listed just because the DPID was entered in a different format. hexstring is what will be used
Piggybacked here is the display of special ports in any flow-mod JSON serialization. This avoids the display of negative numbers for ports like "in_port", "local", etc. Instead, their string keys will be displayed
=> Convert any format DPID to hex string DPID for static entry pusher's 'switch' key

build.xml
allow ant to read project version and name from pom.xml. Ideally, we'd put these constants in a separate file, but maven does not allow these tags to contain variable values
=> Set version and name when compiling using ant

src/main/java/net/floodlightcontroller/core/internal/Controller.java, src/main/java/net/floodlightcontroller/core/internal/RoleManager.java, src/main/java/net/floodlightcontroller/core/web/ControllerRoleResource.java, src/main/resources/floodlightdefault.properties
Add new option in properties to allow user to choose behavior upon transition to STANDBY. Default w/o setting in properties is to keep the controller running and wait for a transition to ACTIVE before dispatching any messages to modules. Since HA support hasn't been widely integrated in the controller, this default is overridden in floodlightdefault.properties to shutdown the controller when a transition to STANDBY takes place.
=> Trivial support for HA role setting in REST API

src/main/java/net/floodlightcontroller/topology/TopologyInstance.java
There won't be any utilization data if we've just turned on the statistics service.
=> Fix utilization link costs

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/resources/floodlightdefault.properties
Add new detailed-match property to define source and destination addresses/ports to match on in each layer. Also add in-port as an optional match for the existing match property.
New:
-- in-port
-- src-mac
-- dst-mac
-- src-ip
-- dst-ip
-- src-transport
-- dat-transport
The behavior is if the general header/layer match is not specified, the detailed match will not be performed.
=> Add detailed-match property to Forwarding

src/main/java/net/floodlightcontroller/routing/ForwardingBase.java
ForwardingBase should also abide by Forwarding's match fields, including in-port.
=> Each hop of path should optionally ignore in-port in flow match

src/main/java/net/floodlightcontroller/core/util/AppCookie.java, src/main/java/net/floodlightcontroller/core/util/AppIDInUseException.java, src/main/java/net/floodlightcontroller/core/util/AppIDNotRegisteredException.java, src/main/java/net/floodlightcontroller/firewall/Firewall.java, src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/test/java/net/floodlightcontroller/core/util/AppCookieTest.java, src/test/java/net/floodlightcontroller/firewall/FirewallTest.java, src/test/java/net/floodlightcontroller/forwarding/ForwardingTest.java
When a link or port fails, we should remove the flows to/from the port(s). This works great in some simple topologies, but in a general case, the flows on the "source" side of the link all the way to the source device will remain installed until either they timeout (a few seconds idle) or the source device stops generating traffic. The flows on the "destination" side of the link all the way to the destination device will time out after the idle timeout interval. 
So, the problem is primarily on the source side, which might result in flows that are never removed. This means that if there are multiple paths available in the topology and the chosen link fails, the packets will never be able to be rerouted to another available link until the source device ceases all traffic, the flows expire, …
=> Improve Forwarding link/port down handler

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
Allow retrieval of VLAN tag from packet-in match. The VLAN tag might be here if the switch popped the VLAN tag from the packet itself prior to encapsulating it in the packet-in message.
=> Extract possible VLAN tag from packet-in's match

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
OpenFlow versions 1.0 and 1.1 do not have a match in their packet-in messages
=> Fix forwarding bug

src/main/java/net/floodlightcontroller/statistics/web/BandwidthResource.java
Check the value of switchService.getSwitch() to avoid NullPointerException in the case of concurrency switch leave.
=> fix concurrency issue in Statistics

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java, src/main/java/net/floodlightcontroller/loadbalancer/LoadBalancer.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java
We will indicate a path was not found in a uniform fashion through an empty path instead of a null path. 
If getPath(src, dst) is invoked, an empty path will be returned if src == dst or if a path was not found in the case src != dst. It is up to the caller to differentiate between these two cases by comparing src and dst if necessary.
If getPath (src, srcPt, dst, dstPt) is invoked, an empty path will be returned if src == dst and srcPt == dstPt. If src == dst and srcPt != dstPt, the endpoints are on the same switch, and a path of length 2 will be returned. An empty path will also be returned if a path was not found in the case src != dst. It is up to the caller to differentiate between these cases by comparing src and dst if necessary.
=> Improve getPath() functions in IRoutingService

src/main/java/net/floodlightcontroller/topology/TopologyInstance.java
Fix for link cost calculation into TopologyInstance for the metric "utilization". 
It was an erroneous copy-paste from the link-speed case.
=> Fixed link cost calculation

src/main/java/net/floodlightcontroller/staticentry/StaticEntryPusher.java
There was a ConcurrentModificationException error occurring when the LoadBalancer module was used with httperf (relatively high rates) and python's SimpleHTTPServer. 
After modifying HashMap to ConcurrentHashMap as can be seen below, no such errors occurred.
=> Fixed ConcurrentModificationException error in StaticEntryPusher.java

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
tcp_flags are only supported after openflow 1.5 as seen at B.18.7 of openflow spec 1.5.0
=> check openflow version before matching tcp_flags

src/main/java/net/floodlightcontroller/devicemanager/IDevice.java, src/main/java/net/floodlightcontroller/statistics/StatisticsCollector.java
@rizard 
Problem: 
When portStatsInterval set to 1, timeout will going to be 0, which immediate will throw the exception
Fix: 
Change TimeUnit to Milliseconds to give more granularity regarding time-scale, so as to avoid Integer Division problem when collection interval is set to 1.
=> Integer Division Problem at StatisticsCollector

build.xml
@rizard guava library version in build.xml is out-of-date, it was V13.0.1, and it should be V20.0.
Update Google guava library version to the correct one "guava-20.0.jar", so that at the runtime it will be loaded correctly.
=> Fix guava library version in build.xml

src/main/java/net/floodlightcontroller/learningswitch/LearningSwitch.java, src/main/java/net/floodlightcontroller/loadbalancer/LoadBalancer.java, src/main/java/net/floodlightcontroller/routing/ForwardingBase.java, src/main/java/net/floodlightcontroller/topology/TopologyManager.java, src/main/java/net/floodlightcontroller/util/OFMessageUtils.java
@rizard 
@geddings 
Problem:
While building out Packet-Out message in OpenFlow 1.5 environment (i.e., BBDP/LLDP packet-out message), those Packet-Out messages are not built correctly.
Solution:
This is because "in_port" attribute was replaced with a "match" in OpenFlow 1.5, therefore we should use OFMessageUtils.setInPort to correctly build up packet-out messages.
=> Fix bug to correctly build Packet-Out message for OpenFlow 1.5

src/main/java/net/floodlightcontroller/forwarding/Forwarding.java
@rizard @geddings 
Problem : #744 , able to reproduce it locally. The problem is caused by Forwarding module trying to use cookieMask without checking OpenFlow version -- cookieMask property added into OpenFlow spec after OF 1.1. 
Solution : Add OF version check logic before using cookieMask when building FlowDelete message. After that, the Error message eliminated.
=> Fix Error "Property cookieMask not supported in OF 1.0" in Forwarding Module  

src/main/java/net/floodlightcontroller/core/internal/Controller.java, src/main/java/net/floodlightcontroller/perfmon/CumulativeTimeBucket.java, src/main/java/net/floodlightcontroller/perfmon/CumulativeTimeBucketJSONSerializer.java, src/main/java/net/floodlightcontroller/perfmon/IPktInProcessingTimeService.java, src/main/java/net/floodlightcontroller/perfmon/NullPktInProcessingTime.java, src/main/java/net/floodlightcontroller/perfmon/PerfMonToggleResource.java, src/main/java/net/floodlightcontroller/perfmon/PerfWebRoutable.java, src/main/java/net/floodlightcontroller/perfmon/PktInProcessingTime.java
@rizard @geddings 
This pull request fixed:
1) StartTime now is correctly 2) Previously this module only monitor one OF packet performance and reset the counter, which doesn't make sense at all as it is designed for "cumulative time bucket" -- Now it count all OF packets and computes the performance metrics(i.e. avg time in a cumulative amount of time). 3) Also rewrite the REST API.
Please let me know your thoughts, thanks!
=> Fix bugs in PerfMon module 

src/main/java/net/floodlightcontroller/staticentry/StaticEntries.java
Without this line, the addFlow(String name, OFFlowMod fm, DatapathId swDpid) function in StaticEntryPusher.java won't be able to set the flow cookie even OFFlowMod fm has set the cookie.
=> manually set cookie while adding static entry flow

src/main/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandler.java, src/main/java/net/floodlightcontroller/core/internal/OFSwitchManager.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchHandlerTestBase.java, src/test/java/net/floodlightcontroller/core/internal/OFSwitchHandshakeHandlerVer13Test.java
Setup table default flows is a part of switch handshake process. But
there are cases when we must not alter switch behaviour(set of installed
OF flows). To "cover" such scenarios new boolean option
"setupTablesDefaultFlows" was added for module
net.floodlightcontroller.core.internal.OFSwitchManager.
It it set to "YES" (default), FL will setup table's default rules on
transition to master state(same as current). If it set to "NO", FL will
not setup table's default flows.
New functionality is covered by unit tests
=> Add setup table default flows toggle

src/main/java/net/floodlightcontroller/topology/Archipelago.java, src/main/java/net/floodlightcontroller/topology/TopologyInstance.java
1. Fixed a bug in **identifyArchipelagos()** where in the base case, **archipelagoFromCluster** wasn't getting updated. (It is a requirement for the applied optimization)
2. Optimized **isInSameArchipelago(DatapathId, DatapathId)** and **getArchipelago(DatapathId)** method (O(n<sup>2</sup>) to O(1)).
3. Changed hashCode and equals methods in Archipelago to not include clusters as 2 archipelagos can't have the same or in fact any common cluster(s) at any state of the current **TopologyInstance** of **TopologyManager**. Even in the method **identifyArchipelagos()**, where it attempts to merge the 2 sets, each of them is bipartite already.
4. Reverted **archipelagos** to use Set instead of List because when we need to change a key in HashSet, we are supposed to remove the key, change it and …
=> Topology Bug Fixes & Optimizations
